### ISSUE TITLE
浮動小数点演算例外(内積化に問題発生)

### ISSUE THREAD

**Issue by kouamano** [kouamano/RECURSIVE-SYSTEM#17]
```
./tq.o in=test_ref.2.t out=test_ref.2.ot  -FT -Pin -Pout data=test.csv
```

**Comment by kouamano** [comment]
-Pout オプションで出る

**Comment by kouamano** [comment]
```

Program received signal SIGFPE, Arithmetic exception.                            0x00000000004029a4 in Function_RecursiveCyclic_Print_IProductVal ()              (gdb) bt                                                                         #0  0x00000000004029a4 in Function_RecursiveCyclic_Print_IProductVal ()          #1  0x00000000004033e6 in ExFunction_Recursive_Ser_MultiPrint ()                 #2  0x000000000040399b in Executor ()                                            #3  0x00000000004052cd in main ()                                                (gdb)

```

**Comment by kouamano** [comment]
OK commit
--
以下に戻す。

commit cbd0f95a4cd94b57df843ac7f84289427ff73bf7                                  
Author: kouamano                                            
Date:   Mon Jun 17 19:49:57 2019 +0900

**Comment by kouamano** [comment]
一旦、すべてのbranchを、cbd0f95a4cd94b57df843ac7f84289427ff73bf7　に統一

**Comment by kouamano** [comment]
後に、README、check.txt　辞書例をadd    、一旦すべてのbranchを以下に統一。


86e6799162a2b596d1abca083ccf766fed2ef575
--
